name: OpenAPI Check

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  openapi:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: actions/checkout@v5
      - uses: actions/setup-node@v4
        with:
          node-version: "22"


      - name: Install OpenAPI tools
        run: npm install -g @stoplight/spectral-cli swagger-cli

      - name: Lint OpenAPI
        run: spectral lint auth-service/api/auth.v1.yaml


      - name: Validate OpenAPI
        run: swagger-cli validate auth-service/api/auth.v1.yaml
